// Detailed copy for the Programs section (03) modals.
// Keyed by language → category id → item index (matching TRANSLATIONS[lang].programs.data order).
// Source: 르셀청담 시술북 2026 (PROCEDURE BOOK 2026).

const PROGRAM_DETAILS = {
  KR: {
    stemcell: [
      {
        cat: "Stem Cell & Longevity · 자가 세포 기반 재생 케어",
        tagline: "혈액 기반 회복 환경을 고려해, 용량·회차로 설계하는 케어",
        desc: "롱제비티 리커버리 프로그램은 자신의 혈액에서 얻은 성분을 활용해, 컨디션과 피부·두피의 회복 환경을 함께 살피는 재생 케어입니다. 정맥 적용과 국소 인젝션을 중심으로 활성화 케어·고압산소·PBM(광생체조절)을 단계적으로 더하며, 용량(60·120·240CC)과 회차(I·III)에 따라 검사·탄력 레이저까지 확장됩니다. 적용 범위와 일정은 사전 상담과 검사 결과에 따라 설계하며, 결과는 개인의 상태에 따라 다를 수 있습니다.",
        steps: ["정맥 적용 — 컨디션·회복 환경 정돈", "PPP 인젝션(얼굴·두피) — 국소 피부·두피 케어", "활성화 케어·고압산소·PBM — 시술 후 회복 보조", "(240·III) 검사·탄력 레이저 연계"],
        programs: [
          { name: "Micro Longevity", tier: "60CC · 피부 집중", note: "피부 중심 가벼운 케어" },
          { name: "Longevity Recovery 120", tier: "120CC · I", note: "입문 케어" },
          { name: "Longevity Recovery 120 III", tier: "120CC · III", note: "회차 기반 정규 코스" },
          { name: "Longevity Recovery 240", tier: "240CC · I", note: "검사 기반 충분한 케어" },
          { name: "Longevity Recovery 240 III", tier: "240CC · III", note: "검사·탄력 통합 코스" },
        ],
        meta: [
          { k: "시술 시간", v: "40~90분 (구성별)" },
          { k: "회복 안내", v: "대부분 일상 가능 / 멍·붓기 가능" },
          { k: "마취 방법", v: "무마취 또는 국소·표면마취" },
          { k: "시술 주기", v: "주기·코스 상담 설계" },
        ],
      },
      {
        cat: "Stem Cell & Longevity · 자가 세포 기반 재생 케어",
        tagline: "PRP 기반 회복 환경 케어 — 피부 부스트부터 정규 코스까지",
        desc: "롱제비티 프라임 P 프로그램은 자신의 혈액에서 분리한 PRP를 활용해, 피부 속 환경과 컨디션을 함께 살피는 회복 케어입니다. PRP를 더마샤인·얼굴·두피 인젝 등 목적에 맞게 적용하고, 스킨부스터와 고압산소·PBM(광생체조절)을 더해 시술 전후 환경을 정돈합니다. 용량·회차에 따라 검사·탄력 레이저·헤어 케어까지 확장되며, 구성과 일정은 사전 상담을 통해 결정합니다. 효과는 점진적으로 나타나고 결과는 개인차가 있을 수 있습니다.",
        steps: ["PRP 인젝션 — 국소 회복 환경 케어", "스킨부스터 — 피부 속 환경 보조", "(120 III) 검사·탄력 레이저·헤어퓨 연계"],
        programs: [
          { name: "Longevity Prime P Skin Boost", tier: "20–40CC · Skin", note: "가벼운 피부 PRP 부스트" },
          { name: "Longevity Prime P 120", tier: "120CC · I", note: "기본 케어 프로그램" },
          { name: "Longevity Prime P 120 III", tier: "120CC · III", note: "탄력·두피 통합 코스" },
        ],
        meta: [
          { k: "시술 시간", v: "40~90분 (구성별)" },
          { k: "회복 안내", v: "대부분 일상 가능 / 멍·붓기 가능" },
          { k: "마취 방법", v: "무마취 또는 국소·표면마취" },
          { k: "시술 주기", v: "상담 후 주기·코스 설계" },
        ],
      },
      {
        cat: "Stem Cell & Longevity · 자가 세포 기반 재생 케어",
        tagline: "골수 유래 자원을 활용한 재생 케어 — 용량별 설계",
        desc: "셀룰 드 무엘 프로그램은 골수 유래 자원을 활용해 개인의 상태와 목적에 맞춰 설계하는 재생 케어입니다. 의료진 판단에 따라 자가 자원을 적용하며, 컨디션을 함께 살피는 케어와 국소 부위 중심의 케어 가운데 선택할 수 있습니다. 활성화 케어와 전후 검사를 함께 구성하고, 용량(60·120CC)에 따라 입문부터 체계적 케어까지 단계별로 설계합니다. 채취와 진행은 사전 상담·검사 결과를 바탕으로 신중히 결정하며, 결과는 개인의 상태에 따라 다를 수 있습니다.",
        steps: ["적용 방식 — 의료진 판단에 따라 선택", "활성화 케어 + 검사 — 단계 관리·상태 점검"],
        programs: [
          { name: "Cellules de Moelle 60", tier: "60CC", note: "입문 케어" },
          { name: "Cellules de Moelle 120", tier: "120CC", note: "전후 검사 기반 체계적 케어" },
        ],
        meta: [
          { k: "시술 시간", v: "90분 내외 (채취 포함, 상담 후 확정)" },
          { k: "회복 안내", v: "채취 부위 통증·멍·출혈 가능" },
          { k: "마취 방법", v: "국소마취 (방식은 상담 후 결정)" },
          { k: "시술 주기", v: "상담 후 주기" },
        ],
      },
      {
        cat: "Stem Cell & Longevity · 자가 세포 기반 재생 케어",
        tagline: "혈장 교환을 기반으로 컨디션을 살피는 의료 케어 — 회차별 관리",
        desc: "플라즈마 리셋 프로그램은 혈장 교환을 기반으로, 의료진의 평가와 모니터링 아래 컨디션을 살피는 의료 케어입니다. 혈장 교환에 활성화 케어, 전후 혈액(·유전자) 검사, 고압산소·PBM(광생체조절)을 하나의 흐름으로 구성합니다. 회차(I·II)에 따라 단회 케어부터 검사 기반 회차 관리까지 설계하며, II 단계에서는 유전자 검사를 추가합니다. 적용 여부는 사전 상담·검사 결과에 따라 신중히 결정하며, 결과는 개인의 상태에 따라 다를 수 있습니다.",
        steps: ["혈장 교환 — 의료진 모니터링 케어", "활성화 케어 + 전후 검사 — 단계 관리·상태 점검", "(II) 유전자 검사 추가"],
        programs: [
          { name: "Plasma Reset I", tier: "I", note: "컨디션 관리 케어" },
          { name: "Plasma Reset II", tier: "II", note: "검사 기반 회차 관리 코스" },
        ],
        meta: [
          { k: "시술 시간", v: "반일 내외 · 검사·회복 관찰 포함" },
          { k: "회복 안내", v: "어지러움·피로감·저혈압 가능 / 검사·관찰 포함" },
          { k: "마취 방법", v: "마취 없음 / 의료진 모니터링" },
          { k: "시술 주기", v: "상담 후 주기·코스 설계" },
        ],
      },
    ],
    lift: [
      {
        cat: "Sculpture du Visage · 탄력 · 윤곽 밸런싱",
        tagline: "심부 집속 초음파(HIFU) 탄력 케어",
        desc: "리프팅 울트라는 고강도 집속 초음파(HIFU)를 심부에 집속해 열 응고점을 형성하며 탄력을 살피는 케어입니다. 작용 깊이가 다른 장비로 탄력을 단계별로 살피는 리프팅 라인의 한 구성으로, 부위와 상태에 따라 단독으로 적용하거나 시그니처 패키지(TIMELESS 360)와 연계합니다. 적합한 방식은 사전 상담을 통해 결정하며, 효과는 점진적으로 나타나고 개인차가 있을 수 있습니다.",
        steps: ["고강도 집속 초음파(HIFU) — 심부 집속, 열 응고점 형성", "단독 또는 시그니처 패키지(TIMELESS 360) 연계"],
        programs: null,
        meta: [
          { k: "사용 장비", v: "ULTHERA" },
          { k: "시술 시간", v: "30~60분 (장비별 상이)" },
          { k: "회복 안내", v: "대부분 일상 가능 / 일시적 홍조·붓기 가능" },
          { k: "마취 방법", v: "무마취 또는 표면마취" },
          { k: "시술 주기", v: "상담 후 주기" },
        ],
      },
      {
        cat: "Sculpture du Visage · 탄력 · 윤곽 밸런싱",
        tagline: "진피 RF 가온, 콜라겐 환경 정돈",
        desc: "리프팅 써마는 RF로 진피를 넓게 가온해 콜라겐 환경을 정돈하며 탄력을 살피는 케어입니다. 작용 깊이가 다른 장비로 탄력을 단계별로 살피는 리프팅 라인의 한 구성으로, 부위와 상태에 따라 단독으로 적용하거나 시그니처 패키지(TIMELESS 360)와 연계합니다. 적합한 방식은 사전 상담을 통해 결정하며, 효과는 점진적으로 나타나고 개인차가 있을 수 있습니다.",
        steps: ["RF 진피 가온 — 콜라겐 환경 정돈", "단독 또는 시그니처 패키지(TIMELESS 360) 연계"],
        programs: null,
        meta: [
          { k: "사용 장비", v: "THERMAGE FLX · TENSERMA" },
          { k: "시술 시간", v: "30~60분 (장비별 상이)" },
          { k: "회복 안내", v: "대부분 일상 가능 / 일시적 홍조·붓기 가능" },
          { k: "마취 방법", v: "무마취 또는 표면마취" },
          { k: "시술 주기", v: "상담 후 주기" },
        ],
      },
      {
        cat: "Sculpture du Visage · 탄력 · 윤곽 밸런싱",
        tagline: "얼굴선의 밸런스를 고려한 윤곽 케어 — 부위 범위에 맞춘 용량",
        desc: "콘투어 핏은 얼굴선과 부위별 밸런스를 함께 고려해 윤곽을 돕는 르셀의 주사 프로그램입니다. 정해진 한 가지 방식을 일률적으로 적용하기보다, 부위 범위에 맞춰 2/4/6CC 용량을 선택해 필요한 위치에 분할 적용합니다. 부분 라인 정돈부터 얼굴 전반, 넓은 부위까지 범위에 맞춰 조정하며, 성분·디자인·용량은 상담을 통해 결정합니다. 결과는 개인의 상태에 따라 다를 수 있습니다.",
        steps: ["윤곽 밸런싱 — 부위 범위에 맞춘 분할 적용", "성분·용량·부위는 상담 후 결정"],
        programs: [
          { name: "Contour Fit 2CC", tier: "2CC", note: "부분 라인" },
          { name: "Contour Fit 4CC", tier: "4CC", note: "얼굴 전반" },
          { name: "Contour Fit 6CC", tier: "6CC", note: "넓은 부위" },
        ],
        meta: [
          { k: "시술 시간", v: "20~30분" },
          { k: "회복 안내", v: "대부분 일상 가능 / 멍·붓기 가능" },
          { k: "마취 방법", v: "무마취 또는 표면마취" },
          { k: "시술 주기", v: "상담 후 주기" },
        ],
      },
      {
        cat: "Sculpture du Visage · 탄력 · 윤곽 밸런싱",
        tagline: "턱선 라인 정돈을 돕는 부위 케어",
        desc: "멍통 엘레강 콘투어는 이중턱 부위의 라인 정돈을 돕는 주사 케어입니다. 부위와 상태를 살핀 뒤 적용 범위를 정하며, 한 번에 마무리하기보다 회차를 두고 경과를 살피며 진행하는 경우가 많습니다. 회차와 용량은 상담을 통해 개인의 상태에 맞게 결정하고, 효과는 점진적으로 나타나며 결과는 개인차가 있을 수 있습니다.",
        steps: ["이중턱 부위 라인 정돈", "회차를 두고 경과를 살피며 진행"],
        programs: null,
        meta: [
          { k: "시술 시간", v: "20분 내외" },
          { k: "회복 안내", v: "멍·붓기·통증 가능" },
          { k: "마취 방법", v: "무마취 또는 표면마취" },
          { k: "시술 주기", v: "상담 후 주기" },
        ],
      },
    ],
    laser: [
      {
        cat: "Signature Packages · 탄력 · 윤곽 · 재생 통합 설계",
        tagline: "서로 다른 깊이의 장비 + 부스터 + 자가 유래 케어를 단계로 설계",
        desc: "타임리스 360은 서로 다른 깊이에 작용하는 장비와 부스터, 자가 유래 케어를 단계로 묶어 설계한 르셀의 시그니처 라인입니다. 초음파(ULTHERA)와 RF(THERMAGE) 탄력 케어를 기본으로, 등급에 따라 콜라겐 부스터 → 스킨보톡스 → 자가 유래 케어 → VIRTUE RF까지 확장합니다. 합리적 입문(CORE)부터 대표형(SIGNATURE), 고급형(PRESTIGE), 최상위형(CELL REVERSE)까지 목표와 상태에 맞춰 선택하며, 결과는 개인차가 있을 수 있습니다.",
        steps: ["초음파(ULTHERA) + RF(THERMAGE) 탄력 케어 기본", "등급에 따라 콜라겐 부스터 → 스킨보톡스 → 자가 유래 케어 → VIRTUE RF 확장"],
        programs: [
          { name: "Timeless 360 Core", tier: "기본형", note: "탄력 케어 · 합리적 입문" },
          { name: "Timeless 360 Signature", tier: "대표형", note: "탄력·재생 대표 통합" },
          { name: "Timeless 360 Prestige", tier: "고급형", note: "결·모공·탄력 강화" },
          { name: "Timeless 360 Cell Reverse", tier: "최상위형", note: "자가 유래 케어 중심 통합" },
        ],
        meta: [
          { k: "시술 시간", v: "60~120분 (등급별)" },
          { k: "회복 안내", v: "대부분 일상 가능 / 구성별 일시 반응 가능" },
          { k: "마취 방법", v: "무마취 또는 표면마취 (구성별 상이)" },
          { k: "시술 주기", v: "상담 후 주기" },
        ],
      },
      {
        cat: "Signature Packages · 탄력 · 윤곽 · 재생 통합 설계",
        tagline: "층별로 접근하는 프리미엄 리프팅 구성",
        desc: "프리미엄 4-레이어 리프팅은 피부 층별(표피·진피·피하지방·SMAS 등)로 접근하는 프리미엄 리프팅 패키지입니다. 한 가지 방식에 의존하기보다 각 층에 맞는 구성을 단계로 묶어 하나의 흐름으로 설계합니다. 적용 층과 구성은 상담을 통해 개인의 피부 상태에 맞게 결정하며, 효과는 점진적으로 나타나고 결과는 개인차가 있을 수 있습니다.",
        steps: ["피부 층별(표피·진피·피하지방·SMAS) 맞춤 구성", "각 층에 맞는 케어를 단계로 묶어 하나의 흐름으로 설계"],
        programs: null,
        meta: [
          { k: "시술 시간", v: "상담 후 안내" },
          { k: "회복 안내", v: "구성별 회복 안내" },
          { k: "마취 방법", v: "구성에 따라 상이" },
          { k: "시술 주기", v: "상담 후 주기" },
        ],
      },
      {
        cat: "Anti-Âge Total · 단계로 설계하는 복합 케어",
        tagline: "세 단계로 설계한 전신 컨디션 통합 케어",
        desc: "시크릿 리쥬버네이션 사이클은 혈액 기반 케어와 지방 유래 자원을 세 단계로 이어, 전신 컨디션을 하나의 흐름으로 관리하는 르셀의 시그니처 통합 프로그램입니다. 혈액 기반 케어로 회복 환경을 정돈하고, 지방 유래 자원을 활용한 뒤, 다시 혈액 기반 케어로 흐름을 마무리합니다. 각 단계는 앞선 케어와 연결되도록 설계되며, 일정과 구성은 사전 상담과 검사를 바탕으로 개인의 상태에 맞춰 정합니다. 결과는 개인의 상태에 따라 다를 수 있습니다.",
        steps: ["STEP 1 혈액 기반 — 회복 환경 정돈", "STEP 2 지방 유래 자원 케어", "STEP 3 혈액 기반 케어로 흐름 마무리"],
        programs: null,
        meta: [
          { k: "시술 시간", v: "사이클 단위 일정 설계" },
          { k: "회복 안내", v: "단계별 회복 안내" },
          { k: "마취 방법", v: "국소마취 (구성에 따라 상이)" },
          { k: "추천 대상", v: "전신 컨디션 통합 관리를 원하는 분" },
          { k: "시술 주기", v: "상담 후 진행" },
        ],
      },
      {
        cat: "Anti-Âge Total · 단계로 설계하는 복합 케어",
        tagline: "수술 전후 회복 환경을 돕는 맞춤 케어 프로그램",
        desc: "스왕 플로레종 프로그램은 성형수술 후의 회복 흐름을 경과에 맞춰 관리하기 위한 맞춤 케어입니다. 수술 전 자가 PRP 준비에서 시작해, 수술 후에는 경과일(POD)에 맞춘 수액과 고압산소·PBM(광생체조절)을 구성하고, 실밥 제거(S/O) 시점에 마무리 회복 케어를 더합니다. 적용 범위와 방문 시점은 집도 내용과 경과일을 기준으로 안내하며, 전 과정은 의료진 관리 아래 진행되고 결과는 개인차가 있을 수 있습니다.",
        steps: ["수술 전 PRP 준비 — 사전 회복 자원 확보", "POD 단계별 수액·산소 케어 — 경과일 맞춤", "S/O 시점 회복 케어 — 마무리 보조"],
        programs: null,
        meta: [
          { k: "시술 시간", v: "수술 일정 연계" },
          { k: "회복 안내", v: "POD 단계별 방문 / 회복 안내" },
          { k: "마취 방법", v: "시술 구성에 따라 상이" },
          { k: "추천 대상", v: "성형수술 후 컨디션 회복 케어를 원하는 분" },
          { k: "시술 주기", v: "케어 기간 상담 설계" },
        ],
      },
    ],
    booster: [
      {
        cat: "Booster de Régénération · 피부 속 환경 케어",
        tagline: "피부 속 재생 환경을 돕는 스킨부스터 — 용량·수분 옵션",
        desc: "리쥬란 스킨부스터는 연어 DNA 유래 PN(폴리뉴클레오타이드) 성분을 진피에 주입해, 피부 속 환경 케어를 돕는 스킨부스터입니다. 표면에 더하기보다 피부가 본래 가진 환경을 정돈하는 관점으로 접근하며, REJURAN(기본)·PLUS(용량 강화)·HB(수분 케어 추가) 옵션 가운데 상태와 목적에 맞게 선택합니다. 효과는 점진적으로 나타나고 시술 후 미세한 자국이 일시적으로 있을 수 있으며, 권장 주기는 상담을 통해 결정합니다.",
        steps: ["연어 DNA 유래 PN 성분 — 진피 섬유아세포 환경 보조", "기본·PLUS(용량 강화)·HB(수분 케어 추가) 옵션"],
        programs: [
          { name: "Rejuran Skin Booster", tier: "기본", note: "기본 PN 케어" },
          { name: "Rejuran Plus", tier: "PLUS", note: "용량 강화" },
          { name: "Rejuran HB", tier: "HB", note: "수분 케어 추가" },
        ],
        meta: [
          { k: "시술 시간", v: "30분 내외" },
          { k: "회복 안내", v: "시술 후 미세 자국·엠보싱·붉음·멍 가능" },
          { k: "마취 방법", v: "표면마취 또는 국소마취" },
          { k: "시술 주기", v: "권장 주기 상담" },
        ],
      },
      {
        cat: "Booster de Régénération · 피부 속 환경 케어",
        tagline: "수분 케어를 더한 리쥬란 스킨부스터",
        desc: "리쥬란 HB는 연어 DNA 유래 PN 성분에 수분 케어를 더해, 피부 속 환경과 수분을 함께 살피는 스킨부스터 옵션입니다. 표면 보습만으로 닿기 어려운 피부 속 환경을 정돈하는 관점으로 접근하며, 효과는 점진적으로 나타나고 시술 후 미세한 자국이 일시적으로 있을 수 있습니다. 권장 주기는 피부 상태에 맞춰 상담을 통해 결정합니다.",
        steps: ["연어 DNA 유래 PN + 수분 케어", "피부 속 환경·수분 환경을 함께 케어"],
        programs: null,
        meta: [
          { k: "시술 시간", v: "30분 내외" },
          { k: "회복 안내", v: "미세 자국·엠보싱·붉음·멍 가능" },
          { k: "마취 방법", v: "표면마취 또는 국소마취" },
          { k: "시술 주기", v: "권장 주기 상담" },
        ],
      },
      {
        cat: "Booster de Régénération · 피부 속 환경 케어",
        tagline: "피부 속 수분과 결을 돕는 스킨부스터",
        desc: "레스틸렌 스킨부스터는 HA(히알루론산) 기반으로 피부 속 수분·결 케어를 돕는 스킨부스터입니다. 표면 보습만으로 닿기 어려운 진피 층의 수분 환경을 함께 살피며, 한 번의 시술보다 권장 주기에 따라 꾸준히 이어갈 때 환경 케어의 관점에서 접근합니다. 적용 범위와 주기는 피부 상태에 맞춰 상담을 통해 결정하고, 효과는 점진적으로 나타나며 결과는 개인차가 있을 수 있습니다.",
        steps: ["HA(히알루론산) 기반 — 진피 수분 환경 케어", "권장 주기에 따라 꾸준히 이어가는 관점"],
        programs: null,
        meta: [
          { k: "시술 시간", v: "30분 내외" },
          { k: "회복 안내", v: "미세 자국·붉음·멍·엠보싱 가능" },
          { k: "마취 방법", v: "표면마취 또는 국소마취" },
          { k: "시술 주기", v: "권장 주기 상담" },
        ],
      },
      {
        cat: "Pigmentation & Skin Clarity · 피부 톤 · 색소 환경 케어",
        tagline: "피부 톤과 색소 환경을 돕는 주사 케어",
        desc: "에클라 멜라스마는 피부 톤 환경 케어를 돕는 성분으로 구성된 주사 케어입니다. 표면의 색소만 보기보다 피부 톤 환경을 함께 살피는 관점에서 접근하며, 일회성보다 꾸준한 관리를 전제로 설계됩니다. 성분·적용 범위와 주기는 피부 상태에 맞춰 상담을 통해 결정하고, 자외선 관리 등 평소의 케어와 함께 이어갈 때 환경 케어의 관점에서 접근합니다. 효과는 점진적으로 나타나며 결과는 개인차가 있을 수 있습니다.",
        steps: ["피부 톤 환경 케어 성분 주사", "꾸준한 관리·자외선 관리와 함께"],
        programs: null,
        meta: [
          { k: "시술 시간", v: "15분 내외" },
          { k: "회복 안내", v: "대부분 일상 가능 / 멍·통증 가능" },
          { k: "마취 방법", v: "무마취" },
          { k: "시술 주기", v: "권장 주기 상담" },
        ],
      },
    ],
    wellness: [
      {
        cat: "Sculpting au Botox · 부위별 근육 밸런스 설계",
        tagline: "결·모공을 살피는 스킨보톡스",
        desc: "보톡스 뒤 비자지는 보툴리눔 톡신 제제를 얼굴 부위 근육 밸런스에 맞춰 미세하게 설계해, 결·모공 등 피부 인상을 살피는 스킨보톡스 케어입니다. 정해진 양을 일률적으로 적용하기보다 부위별 근육의 상태와 목적에 따라 설계를 조정하며, 제품은 국산 제품과 XEOMIN 가운데 상담 후 선택합니다. 효과는 일정 기간 유지되며, 권장 주기와 결과는 개인의 상태에 따라 다를 수 있습니다.",
        steps: ["얼굴 부위 근육 밸런스에 맞춘 미세 설계", "제품(국산 제품 / XEOMIN)은 상담 후 선택"],
        programs: null,
        meta: [
          { k: "시술 시간", v: "15~20분" },
          { k: "회복 안내", v: "대부분 일상 가능 / 부위별 비대칭·근력저하·뻐근함 가능" },
          { k: "마취 방법", v: "무마취 (스킨보톡스 표면마취 가능)" },
          { k: "시술 주기", v: "권장 주기 상담" },
        ],
      },
      {
        cat: "Sculpting au Botox · 부위별 근육 밸런스 설계",
        tagline: "사각턱·침샘 부위 턱선 인상 케어",
        desc: "린뉴 뒤 멍통은 보툴리눔 톡신 제제를 사각턱·침샘 부위 근육에 맞춰 설계해 턱선 인상을 살피는 케어입니다. 부위별 근육의 역할과 균형을 고려해 설계를 조정하며, 제품은 국산 제품과 XEOMIN 가운데 상담 후 선택합니다. 효과는 일정 기간 유지되며, 권장 주기와 결과는 개인차가 있을 수 있습니다.",
        steps: ["사각턱·침샘 부위 근육 밸런스 설계", "제품(국산 제품 / XEOMIN)은 상담 후 선택"],
        programs: null,
        meta: [
          { k: "시술 시간", v: "10분 내외" },
          { k: "회복 안내", v: "대부분 일상 가능 / 부위별 비대칭·근력저하 가능" },
          { k: "마취 방법", v: "무마취" },
          { k: "시술 주기", v: "권장 주기 상담" },
        ],
      },
      {
        cat: "Sculpting au Botox · 부위별 근육 밸런스 설계",
        tagline: "눈가·미간·입꼬리 표정 부위 케어",
        desc: "보톡스 델리카는 보툴리눔 톡신 제제를 눈가·미간·콧등·입꼬리 등 표정 부위 근육에 맞춰 미세하게 설계해 표정 인상을 살피는 케어입니다. 부위별 근육의 역할과 균형을 함께 고려해 설계를 조정하며, 제품은 국산 제품과 XEOMIN 가운데 상담 후 선택합니다. 효과는 일정 기간 유지되며, 권장 주기와 결과는 개인차가 있을 수 있습니다.",
        steps: ["눈가·미간·콧등·입꼬리 표정 부위 미세 설계", "제품(국산 제품 / XEOMIN)은 상담 후 선택"],
        programs: null,
        meta: [
          { k: "시술 시간", v: "10분 내외" },
          { k: "회복 안내", v: "대부분 일상 가능 / 부위별 비대칭·근력저하 가능" },
          { k: "마취 방법", v: "무마취" },
          { k: "시술 주기", v: "권장 주기 상담" },
        ],
      },
      {
        cat: "Sculpting au Botox · 부위별 근육 밸런스 설계",
        tagline: "어깨·목 라인을 살피는 승모근 케어",
        desc: "린뉴 데폴은 보툴리눔 톡신 제제를 승모근에 맞춰 설계해 어깨·목 라인을 살피는 바디 케어입니다. 부위 근육의 상태와 목적에 따라 설계를 조정하며, 승모근은 고용량이 적용될 수 있어 일시적 근력저하·비대칭이 있을 수 있습니다. 제품은 국산 제품과 XEOMIN 가운데 상담 후 선택하고, 효과는 일정 기간 유지됩니다. 권장 주기와 결과는 개인차가 있을 수 있습니다.",
        steps: ["승모근 부위 설계 — 어깨·목 라인", "제품(국산 제품 / XEOMIN)은 상담 후 선택"],
        programs: null,
        meta: [
          { k: "시술 시간", v: "10~15분" },
          { k: "회복 안내", v: "대부분 일상 가능 / 일시적 근력저하·비대칭 가능" },
          { k: "마취 방법", v: "무마취" },
          { k: "시술 주기", v: "권장 주기 상담" },
        ],
      },
    ],
  },

  EN: {
    stemcell: [
      {
        cat: "Stem Cell & Longevity · Autologous-cell-based regenerative care",
        tagline: "Care designed by dose and session, mindful of the blood-based recovery environment",
        desc: "The Longevity Recovery program uses components drawn from one's own blood to care for the recovery environment of condition, skin, and scalp together. Centered on intravenous application and local injection, it adds activation care, hyperbaric oxygen, and PBM (photobiomodulation) in stages, expanding to diagnostics and firming laser by dose (60·120·240CC) and session (I·III). Scope and schedule are designed from prior consultation and diagnostic results, and outcomes may vary by individual.",
        steps: ["Intravenous application — preparing condition and recovery environment", "PPP injection (face · scalp) — local skin and scalp care", "Activation care · hyperbaric oxygen · PBM — post-procedure recovery support", "(240·III) Linked with diagnostics and firming laser"],
        programs: [
          { name: "Micro Longevity", tier: "60CC · Skin focus", note: "Light, skin-centered care" },
          { name: "Longevity Recovery 120", tier: "120CC · I", note: "Entry care" },
          { name: "Longevity Recovery 120 III", tier: "120CC · III", note: "Session-based standard course" },
          { name: "Longevity Recovery 240", tier: "240CC · I", note: "Diagnostics-based fuller care" },
          { name: "Longevity Recovery 240 III", tier: "240CC · III", note: "Diagnostics + firming integrated course" },
        ],
        meta: [
          { k: "Duration", v: "40–90 min (by composition)" },
          { k: "Recovery", v: "Mostly back to daily life / bruising · swelling possible" },
          { k: "Anesthesia", v: "None or local / topical" },
          { k: "Cycle", v: "Cycle · course designed in consultation" },
        ],
      },
      {
        cat: "Stem Cell & Longevity · Autologous-cell-based regenerative care",
        tagline: "PRP-based recovery-environment care — from skin boost to a full course",
        desc: "The Longevity Prime P program uses PRP separated from one's own blood to care for the skin's inner environment and overall condition. PRP is applied by purpose (dermashine, face, scalp injection), with skin boosters, hyperbaric oxygen, and PBM (photobiomodulation) added to prepare the environment before and after. By dose and session it expands to diagnostics, firming laser, and hair care; composition and schedule are decided in prior consultation. Effects appear gradually and outcomes may vary by individual.",
        steps: ["PRP injection — local recovery-environment care", "Skin booster — supporting the skin's inner environment", "(120 III) Linked with diagnostics, firming laser, and hair care"],
        programs: [
          { name: "Longevity Prime P Skin Boost", tier: "20–40CC · Skin", note: "Light skin PRP boost" },
          { name: "Longevity Prime P 120", tier: "120CC · I", note: "Standard care program" },
          { name: "Longevity Prime P 120 III", tier: "120CC · III", note: "Firming · scalp integrated course" },
        ],
        meta: [
          { k: "Duration", v: "40–90 min (by composition)" },
          { k: "Recovery", v: "Mostly back to daily life / bruising · swelling possible" },
          { k: "Anesthesia", v: "None or local / topical" },
          { k: "Cycle", v: "Cycle · course designed after consultation" },
        ],
      },
      {
        cat: "Stem Cell & Longevity · Autologous-cell-based regenerative care",
        tagline: "Regenerative care using marrow-derived resources — designed by dose",
        desc: "The Cellules de Moelle program uses marrow-derived resources, designed to each person's condition and goals. Autologous resources are applied at the medical team's discretion, choosing between condition-focused care and locally focused care. Activation care and pre/post diagnostics are configured together, and by dose (60·120CC) the program is staged from entry to systematic care. Harvesting and progression are decided carefully from prior consultation and diagnostics, and outcomes may vary by individual.",
        steps: ["Method of application — chosen at the medical team's discretion", "Activation care + diagnostics — staged management and condition checks"],
        programs: [
          { name: "Cellules de Moelle 60", tier: "60CC", note: "Entry care" },
          { name: "Cellules de Moelle 120", tier: "120CC", note: "Systematic care based on pre/post diagnostics" },
        ],
        meta: [
          { k: "Duration", v: "~90 min (incl. harvesting, confirmed after consult)" },
          { k: "Recovery", v: "Pain · bruising · bleeding possible at harvest site" },
          { k: "Anesthesia", v: "Local (method decided after consultation)" },
          { k: "Cycle", v: "Cycle after consultation" },
        ],
      },
      {
        cat: "Stem Cell & Longevity · Autologous-cell-based regenerative care",
        tagline: "Medical care monitoring condition via plasma exchange — managed by session",
        desc: "The Plasma Reset program is medical care that monitors condition under the medical team's assessment, based on plasma exchange. It combines plasma exchange with activation care, pre/post blood (and genetic) diagnostics, and hyperbaric oxygen · PBM (photobiomodulation) into one flow. By session (I·II) it is designed from a single-session care to diagnostics-based session management, with genetic testing added at stage II. Suitability is decided carefully from prior consultation and diagnostics, and outcomes may vary by individual.",
        steps: ["Plasma exchange — care under medical-team monitoring", "Activation care + pre/post diagnostics — staged management and condition checks", "(II) Genetic testing added"],
        programs: [
          { name: "Plasma Reset I", tier: "I", note: "Condition-management care" },
          { name: "Plasma Reset II", tier: "II", note: "Diagnostics-based session-management course" },
        ],
        meta: [
          { k: "Duration", v: "~Half-day · incl. diagnostics & recovery observation" },
          { k: "Recovery", v: "Dizziness · fatigue · low blood pressure possible / incl. observation" },
          { k: "Anesthesia", v: "None / medical-team monitoring" },
          { k: "Cycle", v: "Cycle · course designed after consultation" },
        ],
      },
    ],
    lift: [
      {
        cat: "Sculpture du Visage · Elasticity · contour balancing",
        tagline: "Deep focused-ultrasound (HIFU) firming care",
        desc: "Lifting Ultra focuses high-intensity focused ultrasound (HIFU) into deep layers to form thermal coagulation points and care for elasticity. As part of a lifting line that addresses elasticity in stages with devices of differing depths, it is applied alone or linked with the signature package (TIMELESS 360) by region and condition. The suitable method is decided in prior consultation; effects appear gradually and may vary by individual.",
        steps: ["High-intensity focused ultrasound (HIFU) — deep focus, thermal coagulation points", "Standalone or linked with the signature package (TIMELESS 360)"],
        programs: null,
        meta: [
          { k: "Device", v: "ULTHERA" },
          { k: "Duration", v: "30–60 min (varies by device)" },
          { k: "Recovery", v: "Mostly back to daily life / temporary redness · swelling possible" },
          { k: "Anesthesia", v: "None or topical" },
          { k: "Cycle", v: "Cycle after consultation" },
        ],
      },
      {
        cat: "Sculpture du Visage · Elasticity · contour balancing",
        tagline: "RF dermal heating, restoring the collagen environment",
        desc: "Lifting Therma broadly heats the dermis with RF to restore the collagen environment and care for elasticity. As part of a lifting line that addresses elasticity in stages with devices of differing depths, it is applied alone or linked with the signature package (TIMELESS 360) by region and condition. The suitable method is decided in prior consultation; effects appear gradually and may vary by individual.",
        steps: ["RF dermal heating — restoring the collagen environment", "Standalone or linked with the signature package (TIMELESS 360)"],
        programs: null,
        meta: [
          { k: "Device", v: "THERMAGE FLX · TENSERMA" },
          { k: "Duration", v: "30–60 min (varies by device)" },
          { k: "Recovery", v: "Mostly back to daily life / temporary redness · swelling possible" },
          { k: "Anesthesia", v: "None or topical" },
          { k: "Cycle", v: "Cycle after consultation" },
        ],
      },
      {
        cat: "Sculpture du Visage · Elasticity · contour balancing",
        tagline: "Contour care mindful of facial-line balance — dose matched to the area",
        desc: "Contour Fit is LeCell's injectable program that supports contour while considering facial lines and regional balance together. Rather than applying one fixed method uniformly, it selects a 2/4/6CC dose to the area and applies it in divided placements where needed. It adjusts to scope — from refining a partial line to the whole face and wider areas — with ingredients, design, and dose decided in consultation. Outcomes may vary by individual.",
        steps: ["Contour balancing — divided application matched to the area", "Ingredients · dose · region decided after consultation"],
        programs: [
          { name: "Contour Fit 2CC", tier: "2CC", note: "Partial line" },
          { name: "Contour Fit 4CC", tier: "4CC", note: "Whole face" },
          { name: "Contour Fit 6CC", tier: "6CC", note: "Wider area" },
        ],
        meta: [
          { k: "Duration", v: "20–30 min" },
          { k: "Recovery", v: "Mostly back to daily life / bruising · swelling possible" },
          { k: "Anesthesia", v: "None or topical" },
          { k: "Cycle", v: "Cycle after consultation" },
        ],
      },
      {
        cat: "Sculpture du Visage · Elasticity · contour balancing",
        tagline: "Regional care to refine the jawline",
        desc: "Menton Élégant Contour is injectable care that helps refine the line of the double-chin area. After examining the region and condition, the scope of application is set; rather than finishing in one go, it is often performed over sessions while observing progress. Sessions and dose are decided in consultation to suit each person's condition; effects appear gradually and outcomes may vary by individual.",
        steps: ["Refining the double-chin area line", "Performed over sessions while observing progress"],
        programs: null,
        meta: [
          { k: "Duration", v: "~20 min" },
          { k: "Recovery", v: "Bruising · swelling · pain possible" },
          { k: "Anesthesia", v: "None or topical" },
          { k: "Cycle", v: "Cycle after consultation" },
        ],
      },
    ],
    laser: [
      {
        cat: "Signature Packages · Integrated elasticity · contour · regeneration",
        tagline: "Devices of differing depths + boosters + autologous-derived care, designed in stages",
        desc: "Timeless 360 is LeCell's signature line, weaving devices that act at different depths, boosters, and autologous-derived care into a staged program. Built on ultrasound (ULTHERA) and RF (THERMAGE) firming, it expands by tier to collagen boosters → skin botox → autologous-derived care → VIRTUE RF. Choose by goal and condition, from an accessible entry (CORE) to the flagship (SIGNATURE), advanced (PRESTIGE), and top tier (CELL REVERSE); outcomes may vary by individual.",
        steps: ["Ultrasound (ULTHERA) + RF (THERMAGE) firming as the base", "Expands by tier: collagen booster → skin botox → autologous-derived care → VIRTUE RF"],
        programs: [
          { name: "Timeless 360 Core", tier: "Entry", note: "Firming care · accessible start" },
          { name: "Timeless 360 Signature", tier: "Flagship", note: "Flagship firming + regeneration" },
          { name: "Timeless 360 Prestige", tier: "Advanced", note: "Texture · pore · firming boost" },
          { name: "Timeless 360 Cell Reverse", tier: "Top tier", note: "Autologous-derived care focus" },
        ],
        meta: [
          { k: "Duration", v: "60–120 min (by tier)" },
          { k: "Recovery", v: "Mostly back to daily life / temporary reactions possible by composition" },
          { k: "Anesthesia", v: "None or topical (varies by composition)" },
          { k: "Cycle", v: "Cycle designed after consultation" },
        ],
      },
      {
        cat: "Signature Packages · Integrated elasticity · contour · regeneration",
        tagline: "A premium lifting composition that approaches the skin layer by layer",
        desc: "Premium 4-Layer Lifting is a premium lifting package that approaches the skin by layer (epidermis, dermis, subcutaneous fat, SMAS, etc.). Rather than relying on a single method, it binds a composition suited to each layer into one staged flow. The layers addressed and the composition are decided through consultation to suit each person's skin condition; effects appear gradually and outcomes may vary by individual.",
        steps: ["Tailored composition by skin layer (epidermis · dermis · subcutaneous fat · SMAS)", "Care matched to each layer, bound into a single staged flow"],
        programs: null,
        meta: [
          { k: "Duration", v: "Advised after consultation" },
          { k: "Recovery", v: "Recovery guidance by composition" },
          { k: "Anesthesia", v: "Varies by composition" },
          { k: "Cycle", v: "Cycle after consultation" },
        ],
      },
      {
        cat: "Anti-Âge Total · Combination care designed in stages",
        tagline: "Whole-body condition care designed across three stages",
        desc: "Secret Rejuvenation Cycle links blood-based care and fat-derived resources across three stages, managing whole-body condition as a single flow — LeCell's signature integrated program. Blood-based care prepares the recovery environment, fat-derived resources follow, and blood-based care closes the flow. Each stage is designed to connect with the one before it; schedule and composition are set to each person's condition based on prior consultation and diagnostics. Outcomes may vary by individual.",
        steps: ["STEP 1 Blood-based — preparing the recovery environment", "STEP 2 Fat-derived resource care", "STEP 3 Blood-based care to close the flow"],
        programs: null,
        meta: [
          { k: "Duration", v: "Scheduled by cycle" },
          { k: "Recovery", v: "Recovery guidance by stage" },
          { k: "Anesthesia", v: "Local (varies by composition)" },
          { k: "Recommended for", v: "Those wanting integrated whole-body condition care" },
          { k: "Cycle", v: "Proceeds after consultation" },
        ],
      },
      {
        cat: "Anti-Âge Total · Combination care designed in stages",
        tagline: "Tailored care supporting the pre/post-surgery recovery environment",
        desc: "The Soin Floraison program is tailored care to manage the recovery flow after plastic surgery according to its progress. It begins with autologous PRP preparation before surgery, then configures fluids and hyperbaric oxygen · PBM (photobiomodulation) matched to post-operative day (POD), adding closing recovery care at suture removal (S/O). Scope and visit timing are guided by the surgery performed and post-op day; the whole process runs under medical-team management and outcomes may vary by individual.",
        steps: ["Pre-surgery PRP preparation — securing recovery resources in advance", "POD-staged fluids · oxygen care — matched to post-op day", "Recovery care at S/O — closing support"],
        programs: null,
        meta: [
          { k: "Duration", v: "Linked to surgery schedule" },
          { k: "Recovery", v: "POD-staged visits / recovery guidance" },
          { k: "Anesthesia", v: "Varies by composition" },
          { k: "Recommended for", v: "Those wanting condition recovery care after plastic surgery" },
          { k: "Cycle", v: "Care period designed in consultation" },
        ],
      },
    ],
    booster: [
      {
        cat: "Booster de Régénération · Skin inner-environment care",
        tagline: "A skin booster supporting the skin's inner regenerative environment — dose · hydration options",
        desc: "Rejuran Skin Booster injects salmon-DNA-derived PN (polynucleotide) into the dermis to support the skin's inner-environment care. Rather than adding to the surface, it takes the view of restoring the environment the skin already has, choosing among REJURAN (basic), PLUS (higher dose), and HB (added hydration) options by condition and goal. Effects appear gradually, faint marks may be temporarily present after the procedure, and the recommended cycle is decided in consultation.",
        steps: ["Salmon-DNA-derived PN — supporting the dermal fibroblast environment", "Basic · PLUS (higher dose) · HB (added hydration) options"],
        programs: [
          { name: "Rejuran Skin Booster", tier: "Basic", note: "Basic PN care" },
          { name: "Rejuran Plus", tier: "PLUS", note: "Higher dose" },
          { name: "Rejuran HB", tier: "HB", note: "Added hydration care" },
        ],
        meta: [
          { k: "Duration", v: "~30 min" },
          { k: "Recovery", v: "Faint marks · embossing · redness · bruising possible after" },
          { k: "Anesthesia", v: "Topical or local" },
          { k: "Cycle", v: "Recommended cycle in consultation" },
        ],
      },
      {
        cat: "Booster de Régénération · Skin inner-environment care",
        tagline: "Rejuran skin booster with added hydration care",
        desc: "Rejuran HB adds hydration care to salmon-DNA-derived PN, caring for the skin's inner environment and moisture together as a skin-booster option. It takes the view of restoring the inner environment that surface moisturizing alone cannot reach; effects appear gradually and faint marks may be temporarily present after the procedure. The recommended cycle is decided in consultation to suit the skin's condition.",
        steps: ["Salmon-DNA-derived PN + hydration care", "Caring for the skin's inner environment and moisture together"],
        programs: null,
        meta: [
          { k: "Duration", v: "~30 min" },
          { k: "Recovery", v: "Faint marks · embossing · redness · bruising possible" },
          { k: "Anesthesia", v: "Topical or local" },
          { k: "Cycle", v: "Recommended cycle in consultation" },
        ],
      },
      {
        cat: "Booster de Régénération · Skin inner-environment care",
        tagline: "A skin booster supporting the skin's inner moisture and texture",
        desc: "Restylane Skin Booster is an HA (hyaluronic acid) based skin booster that supports the skin's inner moisture and texture care. It looks after the dermal moisture environment that surface moisturizing alone cannot reach, approached as environment care when continued steadily on a recommended cycle rather than a single procedure. Scope and cycle are decided in consultation to suit the skin's condition; effects appear gradually and outcomes may vary by individual.",
        steps: ["HA (hyaluronic acid) based — dermal moisture-environment care", "Continued steadily on a recommended cycle"],
        programs: null,
        meta: [
          { k: "Duration", v: "~30 min" },
          { k: "Recovery", v: "Faint marks · redness · bruising · embossing possible" },
          { k: "Anesthesia", v: "Topical or local" },
          { k: "Cycle", v: "Recommended cycle in consultation" },
        ],
      },
      {
        cat: "Pigmentation & Skin Clarity · Skin tone · pigment-environment care",
        tagline: "Injectable care supporting skin tone and pigment environment",
        desc: "Éclat Melasma is injectable care composed of ingredients that support skin-tone-environment care. Rather than looking at surface pigment alone, it takes the view of caring for the skin-tone environment together, designed on the premise of steady management rather than a one-off. Ingredients, scope, and cycle are decided in consultation to suit the skin's condition; approached as environment care when continued alongside everyday care such as sun protection. Effects appear gradually and outcomes may vary by individual.",
        steps: ["Injection of skin-tone-environment care ingredients", "Alongside steady management and sun protection"],
        programs: null,
        meta: [
          { k: "Duration", v: "~15 min" },
          { k: "Recovery", v: "Mostly back to daily life / bruising · pain possible" },
          { k: "Anesthesia", v: "None" },
          { k: "Cycle", v: "Recommended cycle in consultation" },
        ],
      },
    ],
    wellness: [
      {
        cat: "Sculpting au Botox · Regional muscle-balance design",
        tagline: "Skin botox caring for texture and pores",
        desc: "Botox du Visage finely designs botulinum toxin to the muscle balance of facial regions, caring for the skin's impression such as texture and pores as a skin-botox care. Rather than applying a fixed amount uniformly, the design is adjusted to each region's muscle condition and purpose; the product is chosen after consultation between a domestic product and XEOMIN. Effects last for a period, and the recommended cycle and outcomes may vary by individual.",
        steps: ["Fine design to the muscle balance of facial regions", "Product (domestic / XEOMIN) chosen after consultation"],
        programs: null,
        meta: [
          { k: "Duration", v: "15–20 min" },
          { k: "Recovery", v: "Mostly back to daily life / regional asymmetry · weakness · tightness possible" },
          { k: "Anesthesia", v: "None (topical possible for skin botox)" },
          { k: "Cycle", v: "Recommended cycle in consultation" },
        ],
      },
      {
        cat: "Sculpting au Botox · Regional muscle-balance design",
        tagline: "Jawline impression care for the masseter · salivary-gland area",
        desc: "Ligne du Menton designs botulinum toxin to the muscles of the masseter and salivary-gland area to care for the jawline impression. The design is adjusted considering the role and balance of regional muscles; the product is chosen after consultation between a domestic product and XEOMIN. Effects last for a period, and outcomes may vary by individual.",
        steps: ["Muscle-balance design for the masseter · salivary-gland area", "Product (domestic / XEOMIN) chosen after consultation"],
        programs: null,
        meta: [
          { k: "Duration", v: "~10 min" },
          { k: "Recovery", v: "Mostly back to daily life / regional asymmetry · weakness possible" },
          { k: "Anesthesia", v: "None" },
          { k: "Cycle", v: "Recommended cycle in consultation" },
        ],
      },
      {
        cat: "Sculpting au Botox · Regional muscle-balance design",
        tagline: "Expression-area care for eyes · glabella · mouth corners",
        desc: "Botox Délicat finely designs botulinum toxin to the muscles of expression areas such as eyes, glabella, nose bridge, and mouth corners to care for the expression impression. The design is adjusted considering the role and balance of regional muscles together; the product is chosen after consultation between a domestic product and XEOMIN. Effects last for a period, and outcomes may vary by individual.",
        steps: ["Fine design for expression areas: eyes · glabella · nose bridge · mouth corners", "Product (domestic / XEOMIN) chosen after consultation"],
        programs: null,
        meta: [
          { k: "Duration", v: "~10 min" },
          { k: "Recovery", v: "Mostly back to daily life / regional asymmetry · weakness possible" },
          { k: "Anesthesia", v: "None" },
          { k: "Cycle", v: "Recommended cycle in consultation" },
        ],
      },
      {
        cat: "Sculpting au Botox · Regional muscle-balance design",
        tagline: "Trapezius care for the shoulder · neck line",
        desc: "Ligne d'Épaule designs botulinum toxin to the trapezius to care for the shoulder and neck line as body care. The design is adjusted to the region's muscle condition and purpose; as the trapezius may receive higher doses, temporary weakness or asymmetry can occur. The product is chosen after consultation between a domestic product and XEOMIN, and effects last for a period. The recommended cycle and outcomes may vary by individual.",
        steps: ["Trapezius design — shoulder · neck line", "Product (domestic / XEOMIN) chosen after consultation"],
        programs: null,
        meta: [
          { k: "Duration", v: "10–15 min" },
          { k: "Recovery", v: "Mostly back to daily life / temporary weakness · asymmetry possible" },
          { k: "Anesthesia", v: "None" },
          { k: "Cycle", v: "Recommended cycle in consultation" },
        ],
      },
    ],
  },

  JP: {
    stemcell: [
      {
        cat: "Stem Cell & Longevity · 自家細胞ベースの再生ケア",
        tagline: "血液ベースの回復環境を考慮し、用量·回数で設計するケア",
        desc: "ロンジェビティ リカバリープログラムは、ご自身の血液から得た成分を活用し、コンディションと肌·頭皮の回復環境をともに見つめる再生ケアです。静脈適用と局所インジェクションを中心に、活性化ケア·高圧酸素·PBM(光生体調節)を段階的に加え、用量(60·120·240CC)と回数(I·III)に応じて検査·弾力レーザーまで拡張します。適用範囲と日程は事前カウンセリングと検査結果に応じて設計し、結果は個人の状態により異なる場合があります。",
        steps: ["静脈適用 — コンディション·回復環境を整える", "PPPインジェクション(顔·頭皮) — 局所の肌·頭皮ケア", "活性化ケア·高圧酸素·PBM — 施術後の回復サポート", "(240·III) 検査·弾力レーザーと連携"],
        programs: [
          { name: "Micro Longevity", tier: "60CC · 肌集中", note: "肌中心の軽めのケア" },
          { name: "Longevity Recovery 120", tier: "120CC · I", note: "入門ケア" },
          { name: "Longevity Recovery 120 III", tier: "120CC · III", note: "回数ベースの正規コース" },
          { name: "Longevity Recovery 240", tier: "240CC · I", note: "検査ベースの十分なケア" },
          { name: "Longevity Recovery 240 III", tier: "240CC · III", note: "検査·弾力の統合コース" },
        ],
        meta: [
          { k: "施術時間", v: "40~90分 (構成別)" },
          { k: "ダウンタイム", v: "ほぼ日常可 / 内出血·腫れの可能性" },
          { k: "麻酔方法", v: "麻酔なし または 局所·表面麻酔" },
          { k: "施術周期", v: "周期·コースをカウンセリングで設計" },
        ],
      },
      {
        cat: "Stem Cell & Longevity · 自家細胞ベースの再生ケア",
        tagline: "PRPベースの回復環境ケア — 肌ブーストから正規コースまで",
        desc: "ロンジェビティ プライム Pプログラムは、ご自身の血液から分離したPRPを活用し、肌の中の環境とコンディションをともに見つめる回復ケアです。PRPをダーマシャイン·顔·頭皮インジェクションなど目的に合わせて適用し、スキンブースターと高圧酸素·PBM(光生体調節)を加えて施術前後の環境を整えます。用量·回数に応じて検査·弾力レーザー·ヘアケアまで拡張し、構成と日程は事前カウンセリングで決定します。効果は徐々に現れ、結果には個人差があります。",
        steps: ["PRPインジェクション — 局所の回復環境ケア", "スキンブースター — 肌の中の環境サポート", "(120 III) 検査·弾力レーザー·ヘアと連携"],
        programs: [
          { name: "Longevity Prime P Skin Boost", tier: "20–40CC · Skin", note: "軽めの肌PRPブースト" },
          { name: "Longevity Prime P 120", tier: "120CC · I", note: "基本ケアプログラム" },
          { name: "Longevity Prime P 120 III", tier: "120CC · III", note: "弾力·頭皮の統合コース" },
        ],
        meta: [
          { k: "施術時間", v: "40~90分 (構成別)" },
          { k: "ダウンタイム", v: "ほぼ日常可 / 内出血·腫れの可能性" },
          { k: "麻酔方法", v: "麻酔なし または 局所·表面麻酔" },
          { k: "施術周期", v: "カウンセリング後に周期·コース設計" },
        ],
      },
      {
        cat: "Stem Cell & Longevity · 自家細胞ベースの再生ケア",
        tagline: "骨髄由来資源を活用した再生ケア — 用量別設計",
        desc: "セリュル ド ムエルプログラムは、骨髄由来資源を活用し、個人の状態と目的に合わせて設計する再生ケアです。医療陣の判断により自家資源を適用し、コンディションをともに見つめるケアと局所部位中心のケアから選択できます。活性化ケアと前後検査をともに構成し、用量(60·120CC)に応じて入門から体系的ケアまで段階的に設計します。採取と進行は事前カウンセリング·検査結果をもとに慎重に決定し、結果は個人の状態により異なる場合があります。",
        steps: ["適用方法 — 医療陣の判断により選択", "活性化ケア + 検査 — 段階管理·状態チェック"],
        programs: [
          { name: "Cellules de Moelle 60", tier: "60CC", note: "入門ケア" },
          { name: "Cellules de Moelle 120", tier: "120CC", note: "前後検査ベースの体系的ケア" },
        ],
        meta: [
          { k: "施術時間", v: "90分前後 (採取含む·カウンセリング後に確定)" },
          { k: "ダウンタイム", v: "採取部位の痛み·内出血·出血の可能性" },
          { k: "麻酔方法", v: "局所麻酔 (方法はカウンセリング後に決定)" },
          { k: "施術周期", v: "カウンセリング後に周期" },
        ],
      },
      {
        cat: "Stem Cell & Longevity · 自家細胞ベースの再生ケア",
        tagline: "血漿交換をベースにコンディションを見つめる医療ケア — 回数別管理",
        desc: "プラズマ リセットプログラムは、血漿交換をベースに、医療陣の評価とモニタリングのもとコンディションを見つめる医療ケアです。血漿交換に活性化ケア、前後の血液(·遺伝子)検査、高圧酸素·PBM(光生体調節)を一つの流れで構成します。回数(I·II)に応じて単回ケアから検査ベースの回数管理まで設計し、II段階では遺伝子検査を追加します。適用の可否は事前カウンセリング·検査結果に応じて慎重に決定し、結果は個人の状態により異なる場合があります。",
        steps: ["血漿交換 — 医療陣モニタリングのケア", "活性化ケア + 前後検査 — 段階管理·状態チェック", "(II) 遺伝子検査を追加"],
        programs: [
          { name: "Plasma Reset I", tier: "I", note: "コンディション管理ケア" },
          { name: "Plasma Reset II", tier: "II", note: "検査ベースの回数管理コース" },
        ],
        meta: [
          { k: "施術時間", v: "半日前後 · 検査·回復観察を含む" },
          { k: "ダウンタイム", v: "めまい·疲労感·低血圧の可能性 / 検査·観察を含む" },
          { k: "麻酔方法", v: "麻酔なし / 医療陣モニタリング" },
          { k: "施術周期", v: "カウンセリング後に周期·コース設計" },
        ],
      },
    ],
    lift: [
      {
        cat: "Sculpture du Visage · 弾力 · 輪郭バランシング",
        tagline: "深部集束超音波(HIFU)の弾力ケア",
        desc: "リフティング ウルトラは、高密度集束超音波(HIFU)を深部に集束して熱凝固点を形成し、弾力を見つめるケアです。作用する深さの異なる装備で弾力を段階別に見つめるリフティングラインの一構成として、部位と状態に応じて単独で適用するか、シグネチャーパッケージ(TIMELESS 360)と連携します。適した方法は事前カウンセリングで決定し、効果は徐々に現れ、個人差があります。",
        steps: ["高密度集束超音波(HIFU) — 深部集束·熱凝固点の形成", "単独 または シグネチャーパッケージ(TIMELESS 360)と連携"],
        programs: null,
        meta: [
          { k: "使用装備", v: "ULTHERA" },
          { k: "施術時間", v: "30~60分 (装備により異なる)" },
          { k: "ダウンタイム", v: "ほぼ日常可 / 一時的な紅潮·腫れの可能性" },
          { k: "麻酔方法", v: "麻酔なし または 表面麻酔" },
          { k: "施術周期", v: "カウンセリング後に周期" },
        ],
      },
      {
        cat: "Sculpture du Visage · 弾力 · 輪郭バランシング",
        tagline: "真皮RF加温、コラーゲン環境を整える",
        desc: "リフティング サーマは、RFで真皮を広く加温してコラーゲン環境を整え、弾力を見つめるケアです。作用する深さの異なる装備で弾力を段階別に見つめるリフティングラインの一構成として、部位と状態に応じて単独で適用するか、シグネチャーパッケージ(TIMELESS 360)と連携します。適した方法は事前カウンセリングで決定し、効果は徐々に現れ、個人差があります。",
        steps: ["RF真皮加温 — コラーゲン環境を整える", "単独 または シグネチャーパッケージ(TIMELESS 360)と連携"],
        programs: null,
        meta: [
          { k: "使用装備", v: "THERMAGE FLX · TENSERMA" },
          { k: "施術時間", v: "30~60分 (装備により異なる)" },
          { k: "ダウンタイム", v: "ほぼ日常可 / 一時的な紅潮·腫れの可能性" },
          { k: "麻酔方法", v: "麻酔なし または 表面麻酔" },
          { k: "施術周期", v: "カウンセリング後に周期" },
        ],
      },
      {
        cat: "Sculpture du Visage · 弾力 · 輪郭バランシング",
        tagline: "顔のラインのバランスを考慮した輪郭ケア — 部位範囲に合わせた用量",
        desc: "コントゥール フィットは、顔のラインと部位別のバランスをともに考慮して輪郭を整えるルセルの注射プログラムです。決まった一つの方式を一律に適用するのではなく、部位範囲に合わせて2/4/6CCの用量を選択し、必要な位置に分割適用します。部分ラインの整えから顔全体、広い部位まで範囲に合わせて調整し、成分·デザイン·用量はカウンセリングで決定します。結果は個人の状態により異なる場合があります。",
        steps: ["輪郭バランシング — 部位範囲に合わせた分割適用", "成分·用量·部位はカウンセリング後に決定"],
        programs: [
          { name: "Contour Fit 2CC", tier: "2CC", note: "部分ライン" },
          { name: "Contour Fit 4CC", tier: "4CC", note: "顔全体" },
          { name: "Contour Fit 6CC", tier: "6CC", note: "広い部位" },
        ],
        meta: [
          { k: "施術時間", v: "20~30分" },
          { k: "ダウンタイム", v: "ほぼ日常可 / 内出血·腫れの可能性" },
          { k: "麻酔方法", v: "麻酔なし または 表面麻酔" },
          { k: "施術周期", v: "カウンセリング後に周期" },
        ],
      },
      {
        cat: "Sculpture du Visage · 弾力 · 輪郭バランシング",
        tagline: "あごのラインの整えを助ける部位ケア",
        desc: "マントン エレガン コントゥールは、二重あご部位のラインの整えを助ける注射ケアです。部位と状態を見たうえで適用範囲を決め、一度で仕上げるよりも回数を分けて経過を見ながら進める場合が多くあります。回数と用量はカウンセリングを通じて個人の状態に合わせて決定し、効果は徐々に現れ、結果には個人差があります。",
        steps: ["二重あご部位のラインの整え", "回数を分けて経過を見ながら進行"],
        programs: null,
        meta: [
          { k: "施術時間", v: "20分前後" },
          { k: "ダウンタイム", v: "内出血·腫れ·痛みの可能性" },
          { k: "麻酔方法", v: "麻酔なし または 表面麻酔" },
          { k: "施術周期", v: "カウンセリング後に周期" },
        ],
      },
    ],
    laser: [
      {
        cat: "Signature Packages · 弾力 · 輪郭 · 再生 統合設計",
        tagline: "異なる深さの装備 + ブースター + 自家由来ケアを段階で設計",
        desc: "タイムレス360は、異なる深さに作用する装備とブースター、自家由来ケアを段階でまとめて設計したルセルのシグネチャーラインです。超音波(ULTHERA)とRF(THERMAGE)の弾力ケアを基本に、グレードに応じてコラーゲンブースター → スキンボトックス → 自家由来ケア → VIRTUE RFまで拡張します。リーズナブルな入門(CORE)から代表型(SIGNATURE)、上級型(PRESTIGE)、最上位型(CELL REVERSE)まで、目標と状態に合わせて選択でき、結果には個人差があります。",
        steps: ["超音波(ULTHERA) + RF(THERMAGE) の弾力ケアが基本", "グレードに応じてコラーゲンブースター → スキンボトックス → 自家由来ケア → VIRTUE RFへ拡張"],
        programs: [
          { name: "Timeless 360 Core", tier: "基本型", note: "弾力ケア · リーズナブルな入門" },
          { name: "Timeless 360 Signature", tier: "代表型", note: "弾力·再生の代表統合" },
          { name: "Timeless 360 Prestige", tier: "上級型", note: "キメ·毛穴·弾力の強化" },
          { name: "Timeless 360 Cell Reverse", tier: "最上位型", note: "自家由来ケア中心の統合" },
        ],
        meta: [
          { k: "施術時間", v: "60~120分 (グレード別)" },
          { k: "ダウンタイム", v: "ほぼ日常可 / 構成により一時的な反応の可能性" },
          { k: "麻酔方法", v: "麻酔なし または 表面麻酔 (構成により異なる)" },
          { k: "施術周期", v: "カウンセリング後に周期設計" },
        ],
      },
      {
        cat: "Signature Packages · 弾力 · 輪郭 · 再生 統合設計",
        tagline: "層別にアプローチするプレミアムリフティング構成",
        desc: "プレミアム4-レイヤー リフティングは、肌の層別(表皮·真皮·皮下脂肪·SMASなど)にアプローチするプレミアムリフティングパッケージです。一つの方式に依存するのではなく、各層に合う構成を段階でまとめて一つの流れに設計します。アプローチする層と構成はカウンセリングを通じて個人の肌状態に合わせて決定し、効果は徐々に現れ、結果には個人差があります。",
        steps: ["肌の層別(表皮·真皮·皮下脂肪·SMAS)に合わせた構成", "各層に合うケアを段階でまとめ、一つの流れに設計"],
        programs: null,
        meta: [
          { k: "施術時間", v: "カウンセリング後にご案内" },
          { k: "ダウンタイム", v: "構成別のダウンタイムご案内" },
          { k: "麻酔方法", v: "構成により異なる" },
          { k: "施術周期", v: "カウンセリング後に周期設計" },
        ],
      },
      {
        cat: "Anti-Âge Total · 段階で設計する複合ケア",
        tagline: "三段階で設計した全身コンディション統合ケア",
        desc: "シークレット リジュベネーション サイクルは、血液ベースのケアと脂肪由来資源を三段階でつなぎ、全身コンディションを一つの流れで管理するルセルのシグネチャー統合プログラムです。血液ベースのケアで回復環境を整え、脂肪由来資源を活用したのち、再び血液ベースのケアで流れを締めくくります。各段階は前のケアと連結するよう設計され、日程と構成は事前カウンセリングと検査をもとに個人の状態に合わせて決めます。結果は個人の状態により異なる場合があります。",
        steps: ["STEP 1 血液ベース — 回復環境を整える", "STEP 2 脂肪由来資源のケア", "STEP 3 血液ベースのケアで流れを締めくくり"],
        programs: null,
        meta: [
          { k: "施術時間", v: "サイクル単位で日程設計" },
          { k: "ダウンタイム", v: "段階別のダウンタイムご案内" },
          { k: "麻酔方法", v: "局所麻酔 (構成により異なる)" },
          { k: "おすすめの方", v: "全身コンディションの統合管理をご希望の方" },
          { k: "施術周期", v: "カウンセリング後に進行" },
        ],
      },
      {
        cat: "Anti-Âge Total · 段階で設計する複合ケア",
        tagline: "手術前後の回復環境を助けるカスタムケアプログラム",
        desc: "スワン フロレゾンプログラムは、美容手術後の回復の流れを経過に合わせて管理するためのカスタムケアです。手術前の自家PRP準備から始まり、手術後には経過日(POD)に合わせた輸液と高圧酸素·PBM(光生体調節)を構成し、抜糸(S/O)の時点で仕上げの回復ケアを加えます。適用範囲と来院時点は執刀内容と経過日を基準にご案内し、全過程は医療陣の管理のもとで進行し、結果には個人差があります。",
        steps: ["手術前PRP準備 — 事前の回復資源を確保", "POD段階別の輸液·酸素ケア — 経過日に合わせて", "S/O時点の回復ケア — 仕上げサポート"],
        programs: null,
        meta: [
          { k: "施術時間", v: "手術日程と連携" },
          { k: "ダウンタイム", v: "POD段階別の来院 / 回復ご案内" },
          { k: "麻酔方法", v: "施術構成により異なる" },
          { k: "おすすめの方", v: "美容手術後のコンディション回復ケアをご希望の方" },
          { k: "施術周期", v: "ケア期間をカウンセリングで設計" },
        ],
      },
    ],
    booster: [
      {
        cat: "Booster de Régénération · 肌の中の環境ケア",
        tagline: "肌の中の再生環境を助けるスキンブースター — 用量·水分オプション",
        desc: "リジュラン スキンブースターは、サーモンDNA由来PN(ポリヌクレオチド)成分を真皮に注入し、肌の中の環境ケアを助けるスキンブースターです。表面に加えるよりも、肌が本来持つ環境を整える観点でアプローチし、REJURAN(基本)·PLUS(用量強化)·HB(水分ケア追加)オプションから状態と目的に合わせて選択します。効果は徐々に現れ、施術後に微細な跡が一時的に残ることがあり、推奨周期はカウンセリングで決定します。",
        steps: ["サーモンDNA由来PN成分 — 真皮線維芽細胞の環境サポート", "基本·PLUS(用量強化)·HB(水分ケア追加)オプション"],
        programs: [
          { name: "Rejuran Skin Booster", tier: "基本", note: "基本PNケア" },
          { name: "Rejuran Plus", tier: "PLUS", note: "用量強化" },
          { name: "Rejuran HB", tier: "HB", note: "水分ケア追加" },
        ],
        meta: [
          { k: "施術時間", v: "30分前後" },
          { k: "ダウンタイム", v: "施術後の微細な跡·エンボス·赤み·内出血の可能性" },
          { k: "麻酔方法", v: "表面麻酔 または 局所麻酔" },
          { k: "施術周期", v: "推奨周期をカウンセリング" },
        ],
      },
      {
        cat: "Booster de Régénération · 肌の中の環境ケア",
        tagline: "水分ケアを加えたリジュラン スキンブースター",
        desc: "リジュラン HBは、サーモンDNA由来PN成分に水分ケアを加え、肌の中の環境と水分をともに見つめるスキンブースターオプションです。表面の保湿だけでは届きにくい肌の中の環境を整える観点でアプローチし、効果は徐々に現れ、施術後に微細な跡が一時的に残ることがあります。推奨周期は肌の状態に合わせてカウンセリングで決定します。",
        steps: ["サーモンDNA由来PN + 水分ケア", "肌の中の環境·水分環境をともにケア"],
        programs: null,
        meta: [
          { k: "施術時間", v: "30分前後" },
          { k: "ダウンタイム", v: "微細な跡·エンボス·赤み·内出血の可能性" },
          { k: "麻酔方法", v: "表面麻酔 または 局所麻酔" },
          { k: "施術周期", v: "推奨周期をカウンセリング" },
        ],
      },
      {
        cat: "Booster de Régénération · 肌の中の環境ケア",
        tagline: "肌の中の水分とキメを助けるスキンブースター",
        desc: "レスチレン スキンブースターは、HA(ヒアルロン酸)ベースで肌の中の水分·キメケアを助けるスキンブースターです。表面の保湿だけでは届きにくい真皮層の水分環境をともに見つめ、一度の施術よりも推奨周期に沿って継続するとき、環境ケアの観点でアプローチします。適用範囲と周期は肌の状態に合わせてカウンセリングで決定し、効果は徐々に現れ、結果には個人差があります。",
        steps: ["HA(ヒアルロン酸)ベース — 真皮の水分環境ケア", "推奨周期に沿って継続する観点"],
        programs: null,
        meta: [
          { k: "施術時間", v: "30分前後" },
          { k: "ダウンタイム", v: "微細な跡·赤み·内出血·エンボスの可能性" },
          { k: "麻酔方法", v: "表面麻酔 または 局所麻酔" },
          { k: "施術周期", v: "推奨周期をカウンセリング" },
        ],
      },
      {
        cat: "Pigmentation & Skin Clarity · 肌トーン · 色素環境ケア",
        tagline: "肌トーンと色素環境を助ける注射ケア",
        desc: "エクラ メラスマは、肌トーン環境ケアを助ける成分で構成された注射ケアです。表面の色素だけを見るよりも肌トーン環境をともに見つめる観点でアプローチし、一回性よりも継続的な管理を前提に設計されます。成分·適用範囲と周期は肌の状態に合わせてカウンセリングで決定し、紫外線管理など普段のケアとともに続けるとき、環境ケアの観点でアプローチします。効果は徐々に現れ、結果には個人差があります。",
        steps: ["肌トーン環境ケア成分の注射", "継続的な管理·紫外線管理とともに"],
        programs: null,
        meta: [
          { k: "施術時間", v: "15分前後" },
          { k: "ダウンタイム", v: "ほぼ日常可 / 内出血·痛みの可能性" },
          { k: "麻酔方法", v: "麻酔なし" },
          { k: "施術周期", v: "推奨周期をカウンセリング" },
        ],
      },
    ],
    wellness: [
      {
        cat: "Sculpting au Botox · 部位別の筋肉バランス設計",
        tagline: "キメ·毛穴を見つめるスキンボトックス",
        desc: "ボトックス デュ ヴィザージュは、ボツリヌストキシン製剤を顔部位の筋肉バランスに合わせて緻密に設計し、キメ·毛穴など肌の印象を見つめるスキンボトックスケアです。決まった量を一律に適用するのではなく、部位別の筋肉の状態と目的に応じて設計を調整し、製品は国産製品とXEOMINからカウンセリング後に選択します。効果は一定期間維持され、推奨周期と結果は個人の状態により異なる場合があります。",
        steps: ["顔部位の筋肉バランスに合わせた緻密な設計", "製品(国産製品 / XEOMIN)はカウンセリング後に選択"],
        programs: null,
        meta: [
          { k: "施術時間", v: "15~20分" },
          { k: "ダウンタイム", v: "ほぼ日常可 / 部位別の非対称·筋力低下·こわばりの可能性" },
          { k: "麻酔方法", v: "麻酔なし (スキンボトックスは表面麻酔可)" },
          { k: "施術周期", v: "推奨周期をカウンセリング" },
        ],
      },
      {
        cat: "Sculpting au Botox · 部位別の筋肉バランス設計",
        tagline: "エラ·唾液腺部位のあごライン印象ケア",
        desc: "リーニュ デュ マントンは、ボツリヌストキシン製剤をエラ·唾液腺部位の筋肉に合わせて設計し、あごラインの印象を見つめるケアです。部位別の筋肉の役割とバランスを考慮して設計を調整し、製品は国産製品とXEOMINからカウンセリング後に選択します。効果は一定期間維持され、結果には個人差があります。",
        steps: ["エラ·唾液腺部位の筋肉バランス設計", "製品(国産製品 / XEOMIN)はカウンセリング後に選択"],
        programs: null,
        meta: [
          { k: "施術時間", v: "10分前後" },
          { k: "ダウンタイム", v: "ほぼ日常可 / 部位別の非対称·筋力低下の可能性" },
          { k: "麻酔方法", v: "麻酔なし" },
          { k: "施術周期", v: "推奨周期をカウンセリング" },
        ],
      },
      {
        cat: "Sculpting au Botox · 部位別の筋肉バランス設計",
        tagline: "目元·眉間·口角の表情部位ケア",
        desc: "ボトックス デリカは、ボツリヌストキシン製剤を目元·眉間·鼻筋·口角など表情部位の筋肉に合わせて緻密に設計し、表情の印象を見つめるケアです。部位別の筋肉の役割とバランスをともに考慮して設計を調整し、製品は国産製品とXEOMINからカウンセリング後に選択します。効果は一定期間維持され、結果には個人差があります。",
        steps: ["目元·眉間·鼻筋·口角の表情部位の緻密な設計", "製品(国産製品 / XEOMIN)はカウンセリング後に選択"],
        programs: null,
        meta: [
          { k: "施術時間", v: "10分前後" },
          { k: "ダウンタイム", v: "ほぼ日常可 / 部位別の非対称·筋力低下の可能性" },
          { k: "麻酔方法", v: "麻酔なし" },
          { k: "施術周期", v: "推奨周期をカウンセリング" },
        ],
      },
      {
        cat: "Sculpting au Botox · 部位別の筋肉バランス設計",
        tagline: "肩·首のラインを見つめる僧帽筋ケア",
        desc: "リーニュ デポールは、ボツリヌストキシン製剤を僧帽筋に合わせて設計し、肩·首のラインを見つめるボディケアです。部位の筋肉の状態と目的に応じて設計を調整し、僧帽筋は高用量が適用されることがあり、一時的な筋力低下·非対称が生じる場合があります。製品は国産製品とXEOMINからカウンセリング後に選択し、効果は一定期間維持されます。推奨周期と結果には個人差があります。",
        steps: ["僧帽筋部位の設計 — 肩·首のライン", "製品(国産製品 / XEOMIN)はカウンセリング後に選択"],
        programs: null,
        meta: [
          { k: "施術時間", v: "10~15分" },
          { k: "ダウンタイム", v: "ほぼ日常可 / 一時的な筋力低下·非対称の可能性" },
          { k: "麻酔方法", v: "麻酔なし" },
          { k: "施術周期", v: "推奨周期をカウンセリング" },
        ],
      },
    ],
  },

  CN: {
    stemcell: [
      {
        cat: "Stem Cell & Longevity · 自体细胞再生护理",
        tagline: "考虑血液基础恢复环境，按剂量·次数设计的护理",
        desc: "Longevity Recovery 项目运用从自身血液中提取的成分，一同审视身体状态与肌肤·头皮恢复环境的再生护理。以静脉应用与局部注射为中心，分阶段加入活化护理·高压氧·PBM(光生物调节)，并依剂量(60·120·240CC)与次数(I·III)延伸至检查·弹力激光。适用范围与日程依事前咨询与检查结果设计，结果因个人状态而异。",
        steps: ["静脉应用 — 整顿身体状态·恢复环境", "PPP 注射(面部·头皮) — 局部肌肤·头皮护理", "活化护理·高压氧·PBM — 术后恢复辅助", "(240·III) 衔接检查·弹力激光"],
        programs: [
          { name: "Micro Longevity", tier: "60CC · 肌肤集中", note: "以肌肤为主的轻度护理" },
          { name: "Longevity Recovery 120", tier: "120CC · I", note: "入门护理" },
          { name: "Longevity Recovery 120 III", tier: "120CC · III", note: "以次数为基础的正规课程" },
          { name: "Longevity Recovery 240", tier: "240CC · I", note: "以检查为基础的充分护理" },
          { name: "Longevity Recovery 240 III", tier: "240CC · III", note: "检查·弹力综合课程" },
        ],
        meta: [
          { k: "项目时间", v: "40~90分钟 (按构成)" },
          { k: "恢复说明", v: "多数可正常生活 / 或有淤青·肿胀" },
          { k: "麻醉方式", v: "无麻醉或局部·表面麻醉" },
          { k: "项目周期", v: "周期·课程咨询设计" },
        ],
      },
      {
        cat: "Stem Cell & Longevity · 自体细胞再生护理",
        tagline: "以 PRP 为基础的恢复环境护理 — 从肌肤焕活到正规课程",
        desc: "Longevity Prime P 项目运用从自身血液分离的 PRP，一同审视肌肤内环境与身体状态的恢复护理。将 PRP 按目的(水光、面部、头皮注射等)应用，并加入皮肤精华与高压氧·PBM(光生物调节)以整顿术前术后环境。依剂量·次数延伸至检查·弹力激光·头皮护理，构成与日程通过事前咨询决定。效果循序渐进，结果因人而异。",
        steps: ["PRP 注射 — 局部恢复环境护理", "皮肤精华 — 辅助肌肤内环境", "(120 III) 衔接检查·弹力激光·头皮护理"],
        programs: [
          { name: "Longevity Prime P Skin Boost", tier: "20–40CC · Skin", note: "轻度肌肤 PRP 焕活" },
          { name: "Longevity Prime P 120", tier: "120CC · I", note: "基础护理项目" },
          { name: "Longevity Prime P 120 III", tier: "120CC · III", note: "弹力·头皮综合课程" },
        ],
        meta: [
          { k: "项目时间", v: "40~90分钟 (按构成)" },
          { k: "恢复说明", v: "多数可正常生活 / 或有淤青·肿胀" },
          { k: "麻醉方式", v: "无麻醉或局部·表面麻醉" },
          { k: "项目周期", v: "咨询后设计周期·课程" },
        ],
      },
      {
        cat: "Stem Cell & Longevity · 自体细胞再生护理",
        tagline: "运用骨髓来源资源的再生护理 — 按剂量设计",
        desc: "Cellules de Moelle 项目运用骨髓来源资源，按个人状态与目的设计的再生护理。依医疗团队判断应用自体资源，可在兼顾整体状态的护理与以局部部位为主的护理之间选择。一并构成活化护理与术前术后检查，依剂量(60·120CC)从入门到体系化护理分阶段设计。采集与进行依事前咨询·检查结果审慎决定，结果因个人状态而异。",
        steps: ["应用方式 — 依医疗团队判断选择", "活化护理 + 检查 — 分阶段管理·状态检查"],
        programs: [
          { name: "Cellules de Moelle 60", tier: "60CC", note: "入门护理" },
          { name: "Cellules de Moelle 120", tier: "120CC", note: "以术前术后检查为基础的体系化护理" },
        ],
        meta: [
          { k: "项目时间", v: "约90分钟 (含采集, 咨询后确定)" },
          { k: "恢复说明", v: "采集部位或有疼痛·淤青·出血" },
          { k: "麻醉方式", v: "局部麻醉 (方式咨询后决定)" },
          { k: "项目周期", v: "咨询后周期" },
        ],
      },
      {
        cat: "Stem Cell & Longevity · 自体细胞再生护理",
        tagline: "以血浆置换为基础审视身体状态的医疗护理 — 按次数管理",
        desc: "Plasma Reset 项目以血浆置换为基础，在医疗团队的评估与监测下审视身体状态的医疗护理。将血浆置换与活化护理、术前术后血液(·基因)检查、高压氧·PBM(光生物调节)构成为一条流程。依次数(I·II)从单次护理到以检查为基础的次数管理进行设计，II 阶段加入基因检查。是否适用依事前咨询·检查结果审慎决定，结果因个人状态而异。",
        steps: ["血浆置换 — 医疗团队监测护理", "活化护理 + 术前术后检查 — 分阶段管理·状态检查", "(II) 加入基因检查"],
        programs: [
          { name: "Plasma Reset I", tier: "I", note: "状态管理护理" },
          { name: "Plasma Reset II", tier: "II", note: "以检查为基础的次数管理课程" },
        ],
        meta: [
          { k: "项目时间", v: "约半日 · 含检查·恢复观察" },
          { k: "恢复说明", v: "或有头晕·疲劳感·低血压 / 含检查·观察" },
          { k: "麻醉方式", v: "无麻醉 / 医疗团队监测" },
          { k: "项目周期", v: "咨询后设计周期·课程" },
        ],
      },
    ],
    lift: [
      {
        cat: "Sculpture du Visage · 弹力 · 轮廓平衡",
        tagline: "深层聚焦超声(HIFU)弹力护理",
        desc: "Lifting Ultra 将高强度聚焦超声(HIFU)聚焦于深层形成热凝固点，审视弹力的护理。作为以作用深度不同的设备分阶段审视弹力的提升系列的一项构成，依部位与状态单独应用，或与招牌套餐(TIMELESS 360)衔接。合适的方式通过事前咨询决定，效果循序渐进，因人而异。",
        steps: ["高强度聚焦超声(HIFU) — 深层聚焦, 形成热凝固点", "单独应用或与招牌套餐(TIMELESS 360)衔接"],
        programs: null,
        meta: [
          { k: "使用设备", v: "ULTHERA" },
          { k: "项目时间", v: "30~60分钟 (依设备而异)" },
          { k: "恢复说明", v: "多数可正常生活 / 或有短暂泛红·肿胀" },
          { k: "麻醉方式", v: "无麻醉或表面麻醉" },
          { k: "项目周期", v: "咨询后周期" },
        ],
      },
      {
        cat: "Sculpture du Visage · 弹力 · 轮廓平衡",
        tagline: "真皮射频加温，整顿胶原蛋白环境",
        desc: "Lifting Therma 以射频对真皮进行大范围加温，整顿胶原蛋白环境，审视弹力的护理。作为以作用深度不同的设备分阶段审视弹力的提升系列的一项构成，依部位与状态单独应用，或与招牌套餐(TIMELESS 360)衔接。合适的方式通过事前咨询决定，效果循序渐进，因人而异。",
        steps: ["射频真皮加温 — 整顿胶原蛋白环境", "单独应用或与招牌套餐(TIMELESS 360)衔接"],
        programs: null,
        meta: [
          { k: "使用设备", v: "THERMAGE FLX · TENSERMA" },
          { k: "项目时间", v: "30~60分钟 (依设备而异)" },
          { k: "恢复说明", v: "多数可正常生活 / 或有短暂泛红·肿胀" },
          { k: "麻醉方式", v: "无麻醉或表面麻醉" },
          { k: "项目周期", v: "咨询后周期" },
        ],
      },
      {
        cat: "Sculpture du Visage · 弹力 · 轮廓平衡",
        tagline: "兼顾脸部线条平衡的轮廓护理 — 按部位范围调整剂量",
        desc: "Contour Fit 是一同考量脸部线条与部位平衡、帮助修饰轮廓的 LeCell 注射项目。比起一律采用固定的单一方式，更依部位范围选择 2/4/6CC 剂量，于所需位置分次应用。从局部线条修整到全脸、较大范围，依范围调整，成分·设计·剂量通过咨询决定。结果因个人状态而异。",
        steps: ["轮廓平衡 — 按部位范围分次应用", "成分·剂量·部位咨询后决定"],
        programs: [
          { name: "Contour Fit 2CC", tier: "2CC", note: "局部线条" },
          { name: "Contour Fit 4CC", tier: "4CC", note: "全脸" },
          { name: "Contour Fit 6CC", tier: "6CC", note: "较大范围" },
        ],
        meta: [
          { k: "项目时间", v: "20~30分钟" },
          { k: "恢复说明", v: "多数可正常生活 / 或有淤青·肿胀" },
          { k: "麻醉方式", v: "无麻醉或表面麻醉" },
          { k: "项目周期", v: "咨询后周期" },
        ],
      },
      {
        cat: "Sculpture du Visage · 弹力 · 轮廓平衡",
        tagline: "帮助修整下颌线条的部位护理",
        desc: "Menton Élégant Contour 是帮助修整双下巴部位线条的注射护理。在审视部位与状态后确定应用范围，比起一次完成，多分次进行、观察经过。次数与剂量通过咨询按个人状态决定，效果循序渐进，结果因人而异。",
        steps: ["双下巴部位线条修整", "分次进行、观察经过"],
        programs: null,
        meta: [
          { k: "项目时间", v: "约20分钟" },
          { k: "恢复说明", v: "或有淤青·肿胀·疼痛" },
          { k: "麻醉方式", v: "无麻醉或表面麻醉" },
          { k: "项目周期", v: "咨询后周期" },
        ],
      },
    ],
    laser: [
      {
        cat: "Signature Packages · 弹力 · 轮廓 · 再生 综合设计",
        tagline: "将不同深度的设备 + 精华 + 自体来源护理分阶段设计",
        desc: "Timeless 360 是将作用于不同深度的设备、精华导入与自体来源护理分阶段组合设计而成的 LeCell 招牌系列。以超声波(ULTHERA)与射频(THERMAGE)弹力护理为基础，依等级延伸至胶原蛋白精华 → 皮肤肉毒 → 自体来源护理 → VIRTUE RF。从入门(CORE)到代表型(SIGNATURE)、高级型(PRESTIGE)、顶级型(CELL REVERSE)，依目标与状态选择，效果因人而异。",
        steps: ["超声波(ULTHERA) + 射频(THERMAGE) 弹力护理为基础", "依等级延伸：胶原蛋白精华 → 皮肤肉毒 → 自体来源护理 → VIRTUE RF"],
        programs: [
          { name: "Timeless 360 Core", tier: "基本型", note: "弹力护理 · 入门之选" },
          { name: "Timeless 360 Signature", tier: "代表型", note: "弹力·再生综合代表" },
          { name: "Timeless 360 Prestige", tier: "高级型", note: "肤质·毛孔·弹力强化" },
          { name: "Timeless 360 Cell Reverse", tier: "顶级型", note: "以自体来源护理为核心的综合" },
        ],
        meta: [
          { k: "项目时间", v: "60~120分钟 (按等级)" },
          { k: "恢复说明", v: "多数可正常生活 / 依构成或有短暂反应" },
          { k: "麻醉方式", v: "无麻醉或表面麻醉 (依构成而异)" },
          { k: "项目周期", v: "咨询后设计周期" },
        ],
      },
      {
        cat: "Signature Packages · 弹力 · 轮廓 · 再生 综合设计",
        tagline: "按肌肤层次进行的高端提升构成",
        desc: "Premium 4-Layer Lifting 是按肌肤层次(表皮·真皮·皮下脂肪·SMAS 等)进行的高端提升套餐。不依赖单一方式，而是将适合各层次的构成分阶段组合，设计成一条流程。所针对的层次与构成将通过咨询、按个人肤况决定，效果循序渐进，结果因人而异。",
        steps: ["按肌肤层次(表皮·真皮·皮下脂肪·SMAS)量身构成", "将适合各层次的护理分阶段组合成一条流程"],
        programs: null,
        meta: [
          { k: "项目时间", v: "咨询后说明" },
          { k: "恢复说明", v: "依构成提供恢复说明" },
          { k: "麻醉方式", v: "依构成而异" },
          { k: "项目周期", v: "咨询后周期" },
        ],
      },
      {
        cat: "Anti-Âge Total · 分阶段设计的复合护理",
        tagline: "以三阶段设计的全身状态综合护理",
        desc: "Secret Rejuvenation Cycle 将血液基础护理与脂肪来源资源以三阶段衔接，把全身状态作为一条流程进行管理，是 LeCell 的招牌综合项目。先以血液基础护理整顿恢复环境，再运用脂肪来源资源，最后以血液基础护理收束整体流程。各阶段设计为与前一护理相衔接，日程与构成依事前咨询与检查、按个人状态决定。结果因人而异。",
        steps: ["STEP 1 血液基础 — 整顿恢复环境", "STEP 2 脂肪来源资源护理", "STEP 3 以血液基础护理收束流程"],
        programs: null,
        meta: [
          { k: "项目时间", v: "以循环为单位设计日程" },
          { k: "恢复说明", v: "分阶段恢复说明" },
          { k: "麻醉方式", v: "局部麻醉 (依构成而异)" },
          { k: "推荐对象", v: "希望进行全身状态综合管理者" },
          { k: "项目周期", v: "咨询后进行" },
        ],
      },
      {
        cat: "Anti-Âge Total · 分阶段设计的复合护理",
        tagline: "帮助调理手术前后恢复环境的定制护理项目",
        desc: "Soin Floraison 项目是为按经过管理整形手术后恢复流程的定制护理。从术前自体 PRP 准备开始，术后依术后天数(POD)构成输液与高压氧·PBM(光生物调节)，并在拆线(S/O)时点加入收尾恢复护理。适用范围与到院时点以手术内容与术后天数为基准说明，全过程在医疗团队管理下进行，结果因人而异。",
        steps: ["术前 PRP 准备 — 预先储备恢复资源", "POD 分阶段输液·氧护理 — 按术后天数", "S/O 时点恢复护理 — 收尾辅助"],
        programs: null,
        meta: [
          { k: "项目时间", v: "与手术日程衔接" },
          { k: "恢复说明", v: "POD 分阶段到院 / 恢复说明" },
          { k: "麻醉方式", v: "依项目构成而异" },
          { k: "推荐对象", v: "希望整形手术后进行状态恢复护理者" },
          { k: "项目周期", v: "护理周期咨询设计" },
        ],
      },
    ],
    booster: [
      {
        cat: "Booster de Régénération · 肌肤内环境护理",
        tagline: "帮助调理肌肤内再生环境的皮肤精华 — 剂量·水分选项",
        desc: "Rejuran Skin Booster 将三文鱼 DNA 来源 PN(多核苷酸)成分注入真皮，帮助调理肌肤内环境的皮肤精华。比起在表面叠加，更以整顿肌肤本身环境的角度切入，可在 REJURAN(基本)·PLUS(剂量加强)·HB(增加水分护理)选项中按状态与目的选择。效果循序渐进，术后或有短暂细微痕迹，建议周期通过咨询决定。",
        steps: ["三文鱼 DNA 来源 PN 成分 — 辅助真皮成纤维细胞环境", "基本·PLUS(剂量加强)·HB(增加水分护理)选项"],
        programs: [
          { name: "Rejuran Skin Booster", tier: "基本", note: "基本 PN 护理" },
          { name: "Rejuran Plus", tier: "PLUS", note: "剂量加强" },
          { name: "Rejuran HB", tier: "HB", note: "增加水分护理" },
        ],
        meta: [
          { k: "项目时间", v: "约30分钟" },
          { k: "恢复说明", v: "术后或有细微痕迹·凸起·泛红·淤青" },
          { k: "麻醉方式", v: "表面麻醉或局部麻醉" },
          { k: "项目周期", v: "建议周期咨询" },
        ],
      },
      {
        cat: "Booster de Régénération · 肌肤内环境护理",
        tagline: "增加水分护理的 Rejuran 皮肤精华",
        desc: "Rejuran HB 在三文鱼 DNA 来源 PN 成分上增加水分护理，一同审视肌肤内环境与水分的皮肤精华选项。以整顿表面保湿难以触及的肌肤内环境的角度切入，效果循序渐进，术后或有短暂细微痕迹。建议周期依肤况通过咨询决定。",
        steps: ["三文鱼 DNA 来源 PN + 水分护理", "一同护理肌肤内环境·水分环境"],
        programs: null,
        meta: [
          { k: "项目时间", v: "约30分钟" },
          { k: "恢复说明", v: "或有细微痕迹·凸起·泛红·淤青" },
          { k: "麻醉方式", v: "表面麻醉或局部麻醉" },
          { k: "项目周期", v: "建议周期咨询" },
        ],
      },
      {
        cat: "Booster de Régénération · 肌肤内环境护理",
        tagline: "帮助调理肌肤内水分与肤质的皮肤精华",
        desc: "Restylane Skin Booster 是以 HA(透明质酸)为基础、帮助调理肌肤内水分·肤质的皮肤精华。一同审视表面保湿难以触及的真皮层水分环境，比起单次护理，更在依建议周期持续进行时，以环境护理的角度切入。适用范围与周期依肤况通过咨询决定，效果循序渐进，结果因人而异。",
        steps: ["以 HA(透明质酸)为基础 — 真皮水分环境护理", "依建议周期持续进行的角度"],
        programs: null,
        meta: [
          { k: "项目时间", v: "约30分钟" },
          { k: "恢复说明", v: "或有细微痕迹·泛红·淤青·凸起" },
          { k: "麻醉方式", v: "表面麻醉或局部麻醉" },
          { k: "项目周期", v: "建议周期咨询" },
        ],
      },
      {
        cat: "Pigmentation & Skin Clarity · 肤色 · 色素环境护理",
        tagline: "帮助调理肤色与色素环境的注射护理",
        desc: "Éclat Melasma 是由帮助调理肤色环境的成分构成的注射护理。比起只看表面色素，更以一同审视肤色环境的角度切入，以持续管理为前提而非一次性设计。成分·适用范围与周期依肤况通过咨询决定，与防晒等日常护理一同持续进行时，以环境护理的角度切入。效果循序渐进，结果因人而异。",
        steps: ["注射调理肤色环境的成分", "与持续管理·防晒一同进行"],
        programs: null,
        meta: [
          { k: "项目时间", v: "约15分钟" },
          { k: "恢复说明", v: "多数可正常生活 / 或有淤青·疼痛" },
          { k: "麻醉方式", v: "无麻醉" },
          { k: "项目周期", v: "建议周期咨询" },
        ],
      },
    ],
    wellness: [
      {
        cat: "Sculpting au Botox · 部位肌肉平衡设计",
        tagline: "审视肤质·毛孔的水光肉毒",
        desc: "Botox du Visage 将肉毒杆菌素制剂按面部部位肌肉平衡进行精细设计，审视肤质·毛孔等肌肤印象的水光肉毒护理。比起一律采用固定剂量，更依各部位肌肉状态与目的调整设计，产品在国产产品与 XEOMIN 之间咨询后选择。效果维持一段时间，建议周期与结果因个人状态而异。",
        steps: ["按面部部位肌肉平衡进行精细设计", "产品(国产产品 / XEOMIN)咨询后选择"],
        programs: null,
        meta: [
          { k: "项目时间", v: "15~20分钟" },
          { k: "恢复说明", v: "多数可正常生活 / 或有部位不对称·肌力下降·酸胀" },
          { k: "麻醉方式", v: "无麻醉 (水光肉毒可表面麻醉)" },
          { k: "项目周期", v: "建议周期咨询" },
        ],
      },
      {
        cat: "Sculpting au Botox · 部位肌肉平衡设计",
        tagline: "方下颌·唾液腺部位的下颌印象护理",
        desc: "Ligne du Menton 将肉毒杆菌素制剂按方下颌·唾液腺部位肌肉设计，审视下颌线条印象的护理。考量各部位肌肉的作用与平衡调整设计，产品在国产产品与 XEOMIN 之间咨询后选择。效果维持一段时间，结果因人而异。",
        steps: ["方下颌·唾液腺部位肌肉平衡设计", "产品(国产产品 / XEOMIN)咨询后选择"],
        programs: null,
        meta: [
          { k: "项目时间", v: "约10分钟" },
          { k: "恢复说明", v: "多数可正常生活 / 或有部位不对称·肌力下降" },
          { k: "麻醉方式", v: "无麻醉" },
          { k: "项目周期", v: "建议周期咨询" },
        ],
      },
      {
        cat: "Sculpting au Botox · 部位肌肉平衡设计",
        tagline: "眼周·眉间·嘴角的表情部位护理",
        desc: "Botox Délicat 将肉毒杆菌素制剂按眼周·眉间·鼻背·嘴角等表情部位肌肉精细设计，审视表情印象的护理。一并考量各部位肌肉的作用与平衡调整设计，产品在国产产品与 XEOMIN 之间咨询后选择。效果维持一段时间，结果因人而异。",
        steps: ["眼周·眉间·鼻背·嘴角表情部位的精细设计", "产品(国产产品 / XEOMIN)咨询后选择"],
        programs: null,
        meta: [
          { k: "项目时间", v: "约10分钟" },
          { k: "恢复说明", v: "多数可正常生活 / 或有部位不对称·肌力下降" },
          { k: "麻醉方式", v: "无麻醉" },
          { k: "项目周期", v: "建议周期咨询" },
        ],
      },
      {
        cat: "Sculpting au Botox · 部位肌肉平衡设计",
        tagline: "审视肩颈线条的斜方肌护理",
        desc: "Ligne d'Épaule 将肉毒杆菌素制剂按斜方肌设计，审视肩颈线条的身体护理。依部位肌肉状态与目的调整设计，斜方肌可能采用较高剂量，或出现短暂肌力下降·不对称。产品在国产产品与 XEOMIN 之间咨询后选择，效果维持一段时间。建议周期与结果因人而异。",
        steps: ["斜方肌部位设计 — 肩颈线条", "产品(国产产品 / XEOMIN)咨询后选择"],
        programs: null,
        meta: [
          { k: "项目时间", v: "10~15分钟" },
          { k: "恢复说明", v: "多数可正常生活 / 或有短暂肌力下降·不对称" },
          { k: "麻醉方式", v: "无麻醉" },
          { k: "项目周期", v: "建议周期咨询" },
        ],
      },
    ],
  },
};

window.PROGRAM_DETAILS = PROGRAM_DETAILS;
